# Numpy_Arrays

In [1]:
import numpy as np

In [10]:
 np.array([1,2,5,6,'Li','rose',False])

array(['1', '2', '5', '6', 'Li', 'rose', 'False'], dtype='<U11')

In [12]:
mynumpy_Sample =np.array([1,2,3,4,5,.6,7])

In [5]:
mylist_Sample = [1,23,55,'Lily']

In [6]:
mylist_Sample*2

[1, 23, 55, 'Lily', 1, 23, 55, 'Lily']

In [13]:
mynumpy_Sample * 2

array([ 2. ,  4. ,  6. ,  8. , 10. ,  1.2, 14. ])

In [19]:
a =[[1,2,3],[4,5,[2,5,8]],[7,8,9]]

In [20]:
np.array(a)

array([[1, 2, 3],
       [4, 5, list([2, 5, 8])],
       [7, 8, 9]], dtype=object)

In [21]:
# Access Elements in a matrix
a[2][1]
a[1][2]
a[1][2][1]

5

In [24]:
#Create a random integers in the interval [0,10]
np.random.randint(0,10,[2,3])

array([[5, 6, 9],
       [6, 4, 4]])

In [25]:
np.random.randint(10,20,[2,3])

array([[15, 11, 15],
       [13, 10, 12]])

# Seed fix the same random generation

In [27]:
np.random.seed(0)
np.random.randint(0,10,[3,3])

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [28]:
np.random.seed(1)
np.random.randint(0,10,[3,3])

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6]])

In [29]:
np.zeros((2,3), dtype =int)

array([[0, 0, 0],
       [0, 0, 0]])

In [30]:
np.ones((3,3), dtype =int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [32]:
#Identity matrix is a square matrix so one input is given
np.identity(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [33]:
#create a matrix with a specific number
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [34]:
np.full((4,3),5.5)

array([[5.5, 5.5, 5.5],
       [5.5, 5.5, 5.5],
       [5.5, 5.5, 5.5],
       [5.5, 5.5, 5.5]])

# Array Concantentaion

In [37]:
matrir1 = np.random.randint(0,20,[4,3])
matrir1

array([[ 5, 18, 11],
       [10, 14, 18],
       [ 4,  9, 17],
       [ 0, 13,  9]])

In [38]:
matrir2 = np.random.randint(0,10,[4,3])
matrir2

array([[9, 7, 6],
       [9, 1, 0],
       [1, 8, 8],
       [3, 9, 8]])

In [39]:
#axis on x
combine = np.concatenate([matrir1, matrir2], axis =0)
combine

array([[ 5, 18, 11],
       [10, 14, 18],
       [ 4,  9, 17],
       [ 0, 13,  9],
       [ 9,  7,  6],
       [ 9,  1,  0],
       [ 1,  8,  8],
       [ 3,  9,  8]])

In [40]:
#axis on y
combine = np.concatenate([matrir1, matrir2], axis =1)
combine

array([[ 5, 18, 11,  9,  7,  6],
       [10, 14, 18,  9,  1,  0],
       [ 4,  9, 17,  1,  8,  8],
       [ 0, 13,  9,  3,  9,  8]])

In [3]:
my_mat = [[1,2,3],[4,5,6],[7,8,9],10]

np.array(my_mat)

array([list([1, 2, 3]), list([4, 5, 6]), list([7, 8, 9]), 10],
      dtype=object)

In [12]:
try:
    my_mat[[1]]
except:
    print('cool')

cool


In [7]:
my_mat[0][2]

3

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [16]:
np.arange(1,9,3)

array([1, 4, 7])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [23]:
np.linspace(1,10,25)

array([ 1.   ,  1.375,  1.75 ,  2.125,  2.5  ,  2.875,  3.25 ,  3.625,
        4.   ,  4.375,  4.75 ,  5.125,  5.5  ,  5.875,  6.25 ,  6.625,
        7.   ,  7.375,  7.75 ,  8.125,  8.5  ,  8.875,  9.25 ,  9.625,
       10.   ])

In [24]:
np.eye(5)  #Identity Matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
#Random Methods

np.random.randn(3)

array([-0.62836383, -1.03536001, -0.11533403])

In [29]:
np.random.rand(5,5)  #No Need to pass tuple here

array([[0.04965876, 0.52631219, 0.77890438, 0.66151963, 0.81670194],
       [0.6496009 , 0.57392111, 0.68166154, 0.21989238, 0.88786946],
       [0.96534233, 0.31711126, 0.25145878, 0.12305437, 0.61941466],
       [0.59921207, 0.7443984 , 0.98361506, 0.76534623, 0.47568129],
       [0.53613379, 0.05432355, 0.11655973, 0.61574442, 0.46482231]])

In [34]:
np.random.randint(1,10,11)

array([5, 7, 6, 9, 8, 2, 1, 8, 3, 6, 7])

In [36]:
#Reshape Method

arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [38]:
narr = np.random.randint(1,10,25)
narr

array([8, 2, 1, 8, 9, 6, 3, 5, 6, 3, 3, 7, 6, 7, 1, 4, 7, 4, 6, 8, 4, 7,
       1, 6, 2])

In [42]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
narr.max()

narr.argmax()   # -> Return the index of maximum value

4

In [48]:
narr.min()
narr.argmin()  ## -> Return the index of minimum value

2

In [50]:
arr.shape

(25,)

In [51]:
arr.reshape(5,5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [52]:
arr.shape

(25,)

In [53]:
arr.dtype

dtype('int32')

*** Numpy Array Indexing***

In [3]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])


***Python list | index()***

index() is an inbuilt function in Python, which searches for given element from start of the list and returns the lowest index where the element appears.

Syntax :

list_name.index(element, start, end)

In [16]:
list=[1,2,3,4,5,6,7,8,9,10,11,12]
list.index(10)

9

In [12]:
sentence = 'Python programming is fun.'

result = sentence.index('is fun')
print("Substring 'is fun':", result)

Substring 'is fun': 19


In [13]:
sentence = 'Python programming is fun.'

# Substring is searched in 'gramming is fun.'
print(sentence.index('ing', 10))

15


In [20]:
arr[15]

15

In [21]:
arr[0:6] = 100

In [22]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [24]:
arr[:] = 101
arr

array([101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101,
       101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])

In [27]:
arr_dd = np.array([[5,10,15],[20,25,50],[75,25,100]])
arr_dd

array([[  5,  10,  15],
       [ 20,  25,  50],
       [ 75,  25, 100]])

In [40]:
#arr_dd[[1]]
arr_dd[2][1]


25

In [45]:
arr_dd[2,1]

25

In [49]:
arr_dd[2:,1]

array([25])

In [52]:
arr_dd[1:2,2:]

array([[50]])

In [53]:
arr_dd[:1,1:]

array([[10, 15]])

In [54]:
arr_dd[:2,1:]

array([[10, 15],
       [25, 50]])

In [55]:
arr_dd

array([[  5,  10,  15],
       [ 20,  25,  50],
       [ 75,  25, 100]])

In [56]:
arr_dd[:2,0:]

array([[ 5, 10, 15],
       [20, 25, 50]])

In [59]:
ar = np.arange(10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
bool_arr = ar >5
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [63]:
ar[bool_arr]

array([6, 7, 8, 9])

In [64]:
ar[ar>5]

array([6, 7, 8, 9])

In [65]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [67]:
arr_2d[2:5,1:5]

array([[21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [68]:
arr_2d[2:4,1:5]

array([[21, 22, 23, 24],
       [31, 32, 33, 34]])

# NumPy_Operations

1. Array with arrays
2. Array with scalars
3. Universal array functions

In [70]:
ar_function = np.arange(0,20)
ar_function

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [72]:
print(ar_function + ar_function)
print(ar_function - ar_function)
print(ar_function * ar_function)
print(ar_function / ar_function)  #invalid value encountered in true_divide i.e., Nan Value (1/0)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289
 324 361]
[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.]


C:\Users\VigneshSS\Anaconda3\envs\new_env\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.


In [73]:
print(ar_function + 100)
print(ar_function - 100)
print(ar_function * 100)

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119]
[-100  -99  -98  -97  -96  -95  -94  -93  -92  -91  -90  -89  -88  -87
  -86  -85  -84  -83  -82  -81]
[   0  100  200  300  400  500  600  700  800  900 1000 1100 1200 1300
 1400 1500 1600 1700 1800 1900]


In [75]:
try:
    1/0
except ZeroDivisionError:
    print('Infinity')

Infinity


In [77]:
1/ar_function             #divide by zero encountered in true_divide              

C:\Users\VigneshSS\Anaconda3\envs\new_env\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158])

In [78]:
ar_function **2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361], dtype=int32)

In [79]:
np.sqrt(ar_function)  #Square_root

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894])

In [81]:
np.exp(ar_function)   #Exponential

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [ ]:
np.max()
np.sin()
np.log()

In [83]:
np.divide(ar_function, 2)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

# Exercise_Solution

In [84]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [85]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [88]:
np.ones(10) *10 

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10.])

In [90]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [93]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [98]:
np.random.rand(1,2) #generate a random number between 1 and 2

array([[0.56789529, 0.87234829]])

In [97]:
np.random.randn(1,2)  #generate a random number between 1 and 2 with standard normalization

array([[0.65538968, 0.08453358]])

In [100]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [101]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [103]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [105]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [114]:
mat[3:,]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [108]:
mat_d = mat[2:,1:]
mat_d

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [106]:
mat_3d = np.array([[12,13,14,15],[17,18,19,20],[22,23,24,25]])
mat_3d

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [113]:
mat[0:3,1]

array([ 2,  7, 12])

In [111]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [112]:
mat[4:,0:]

array([[21, 22, 23, 24, 25]])

In [117]:
np.sum(mat)

325

In [115]:
mat.sum()

325

In [116]:
mat.std()

7.211102550927978

In [120]:
mat.sum(axis =1)

array([ 15,  40,  65,  90, 115])

In [121]:
mat.sum(axis =0) #all the columns

array([55, 60, 65, 70, 75])

-----

# Scipy

SciPy is a open source scientific library for python. The SciPy library depends on NumPy, which provides convenient and fast N-dimensional array manipulation.

In [42]:
# import the scipy library
import scipy

#### `COMPUTE THE Nth DERIVATE OF A FUNCTION`

---

In [43]:
# import the derivative from scipy
from scipy.misc import derivative

# define the function
def my_function(x):
    return x**2 + x + 1

# calculate the first derivative of the function at x = 2

derivative(func= my_function, x0=2)

5.0

In [45]:
#***Now, calculate the second derivative***
derivative(func=my_function,x0=2,n=2)

2.0


#### `PERMUTATION AND COMBINATIONS`

In [46]:
# COMBINATIONS
from scipy.special import comb

# total number of combinations from 4 different values taken 2 at a time
# Value of 4C2
com = comb(4, 2)

print(com)

6.0


In [47]:
# PERMUTATIONS: Value of 4P2
from scipy.special import perm
per = perm(4, 2)

print(per)

12.0



### 'Linear Algebra'

In [48]:
# import linear algebra module and numpy
from scipy import linalg
import numpy as np

# square matrix
matrix = np.array([[1, 5, 2],
                   [3, 2, 1],
                   [1, 2, 1]])

matrix

array([[1, 5, 2],
       [3, 2, 1],
       [1, 2, 1]])

In [50]:
# pass values to det() function determinant of the matrix
linalg.det(matrix)

-1.9999999999999998

In [49]:
# inverse of a matrix
linalg.inv(matrix)

array([[ 0. ,  0.5, -0.5],
       [ 1. ,  0.5, -2.5],
       [-2. , -1.5,  6.5]])

In [122]:
7 **4

2401

In [125]:
s = 'Hi there Sam!0'
ss = s.split()
ss

['Hi', 'there', 'Sam!0']